# Generated by Django 4.1.7 on 2023-03-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'blog_post', 'verbose_name_plural': 'blog_posts'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='blog_post',
        ),
    ]
