# Generated by Django 3.2.18 on 2023-04-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_author_post_author_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
