# Generated by Django 4.1.7 on 2023-04-11 18:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_options_alter_post_author_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="summary",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
