# Generated by Django 3.2.18 on 2023-05-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_blog_profile_friends_+', to='blog.Profile'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
