# Generated by Django 3.2.18 on 2023-05-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_chatmessage_thread'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thread',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_person',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
