# Generated by Django 4.2.1 on 2023-06-12 08:48

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_dialogsmodel_messagemodel_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Texto'),
        ),
        migrations.DeleteModel(
            name='DialogsModel',
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
