# Generated by Django 4.2.1 on 2023-06-29 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0023_thread_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_chat', models.CharField(choices=[('chat', 'chat'), ('group', 'group')], max_length=200, verbose_name='Tipo de chat')),
                ('chat_logo', models.ImageField(null=True, upload_to='media/logo/', verbose_name='Imagem')),
                ('group_name', models.CharField(max_length=200, verbose_name='Nome do grupo')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de atualização')),
                ('participants', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('_state', models.CharField(choices=[('unread', 'unread'), ('read', 'read')], default='unread', max_length=200, verbose_name='Estado')),
                ('message_type', models.CharField(choices=[('text', 'text'), ('image', 'image'), ('video', 'video'), ('audio', 'audio'), ('document', 'document'), ('archive', 'archive')], default='text', max_length=200, verbose_name='Tipo de mensagem')),
                ('_archive', models.FileField(null=True, upload_to='uploads/', verbose_name='Arquivo')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de atualização')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.chat', verbose_name='Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thread',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_person',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
