# Generated by Django 4.2.1 on 2023-07-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
