# Generated by Django 4.2.1 on 2023-07-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_rename_chat_id_message_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterField(
            model_name='message',
            name='_state',
            field=models.CharField(choices=[('unread', 'Não lido'), ('read', 'Lido')], default='unread', max_length=200, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('document', 'Documento'), ('archive', 'Arquivo')], default='text', max_length=200, verbose_name='Tipo de mensagem'),
        ),
    ]
