# Generated by Django 4.2.1 on 2023-07-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_message_options_alter_message__state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='_archive',
            new_name='archive',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='_state',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=1024, verbose_name='Mensagem'),
        ),
    ]
