# Generated by Django 4.2.1 on 2023-07-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_rename__archive_message_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type_chat',
            field=models.CharField(choices=[('chat', 'chat'), ('group', 'group')], default='chat', max_length=200, verbose_name='Tipo de chat'),
        ),
    ]
