# Generated by Django 4.2.1 on 2023-07-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_message_user_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
    ]
