# Generated by Django 4.2.1 on 2023-07-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_message_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
    ]
