# Generated by Django 4.2.1 on 2023-08-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='assunto',
            field=models.CharField(default='Sem categoria', max_length=200, verbose_name='Categoria'),
        ),
    ]
