# Generated by Django 4.2.1 on 2023-08-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_post_assunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='assunto',
            field=models.CharField(max_length=200, verbose_name='Categoria'),
        ),
    ]
