# Generated by Django 4.2.1 on 2023-10-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_post_assunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_logo',
            field=models.ImageField(default='static/images/default-icon.jpg', upload_to='media/logo/', verbose_name='Imagem'),
        ),
    ]
