# Generated by Django 4.2.1 on 2023-10-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_chat_chat_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_logo',
            field=models.ImageField(default='/media/logo/default-icon.jpg', upload_to='media/logo/', verbose_name='Imagem'),
        ),
    ]
