# Generated by Django 4.2.1 on 2023-10-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_alter_chat_chat_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_logo',
            field=models.ImageField(blank=True, upload_to='logo/', verbose_name='Imagem'),
        ),
    ]
